SELECT
    -- Vendas (Tabela Principal)
    V."codigo da empresa",
    V."codigo da venda",
    V."serie da venda",
    V."codigo do cliente",
    V."codigo do vendedor",
    V."data da venda",
    V."valor da venda bruta total",
    V."valor em vale-troca total",
    V."valor da venda liquida total",
    V."quantidade venda bruta total",
    V."quantidade troca total",
    V."quantidade venda liquida total",
    V."custo da venda total",
    V."custo de troca total",
    V.frete,
    V."codigo do produto",
    V."quantidade venda itens",
    V."valor da venda itens",
    V."custo da venda itens",
    V."quantidade troca itens",
    V."valor de troca itens",
    V."custo de troca itens",
    V.hora,
    V."quantidade venda liquida itens",
    V."valor da venda liquida itens",
    V."custo da venda liquida itens",
    V."uk venda",
    V."faixa de valor",
    V."mes de referencia",
    V."fk cliente",
    V."fk vendedores",
    V."fk empresas",
    V."fk produtos",
    V."sistema origem" AS vda_sistema_origem,
    V.operacao,
    V."desconto total",

    -- Clientes_final
    C."pk clientes",
    C."sistema origem" AS cli_sistema_origem,
    C.codigo AS cli_codigo,
    C.nome AS cli_nome,
    C.sexo,
    C.cidade AS cli_cidade,
    C.uf AS cli_uf,
    C.pais AS cli_pais,
    C.ddd,
    C.fone,
    C."ddd celular",
    C.celular,
    C.email,
    C."data de cadastro",
    C."data de nascimento",
    C."codigo do tipo",
    C."filial de cadastro",
    C.idade,
    C."faixa etaria",
    C."data ultima compra",
    C."loja ultima compra",
    C.recencia,
    C.frequencia,
    C."faixa de recencia",
    C."faixa de frequencia",
    C."valor medio",
    C.tipo,
    C.genero,
    C.atividade,
    C."score rfv",
    C."mes de aniversario",
    C."dia de aniversario",
    C."email informado",
    C."fone informado",
    C."celular informado",
    C."nome e sobrenome informado",
    C."endereco informado",

    -- Empresas
    E."pk empresas",
    E."codigo da filial",
    E."codigo da loja",
    E.nome AS emp_nome,
    E."nome reduzido" AS emp_nome_reduzido,
    E.cidade AS emp_cidade,
    E.uf AS emp_uf,
    E.pais AS emp_pais,
    E."rede da loja",
    E.latitude,
    E.longitude,
    E.agrupamento,
    E."supervisor loja",
    E."supervisor salao",
    E."area da loja"

FROM belshop_platinum_db.Vendas AS V
LEFT JOIN belshop_platinum_db.Clientes_final AS C 
    ON V."fk cliente" = C."pk clientes"
LEFT JOIN belshop_platinum_db.Empresas AS E 
    ON V."fk empresas" = E."pk empresas"