SELECT Upper(Rtrim(V.codigo_empresa))                       AS       `Codigo da Empresa`,
       Upper(Rtrim(V.codigo_venda))                          AS       `Codigo da Venda`,
       Upper(Rtrim(V.serie))                                 AS 	  `Serie da Venda`,       
	   Upper(Rtrim(V.codigo_cliente))                        AS       `Codigo do Cliente`,
       Upper(Rtrim(V.codigo_vendedor))                       AS       `Codigo do Vendedor`,
       V.data_venda                                          AS 	  `Data da Venda`,
       V.valor_venda_liquida_total                           AS       `Valor da Venda Bruta Total`,
       V.valor_troca_total                                   AS       `Valor de Troca Total`,
       ( V.valor_venda_liquida_total - V.valor_troca_total ) AS       `Valor da Venda Liquida Total`,
       V.qtde_venda_bruta_total                              AS       `Quantidade Venda Bruta Total`,
       V.qtde_troca_total                                    AS       `Quantidade Troca Total`,
       V.qtde_venda_liquida_total                            AS       `Quantidade Venda Liquida Total`,
       V.custo_venda_total                                   AS       `Custo da Venda Total`,
       V.custo_troca_total                                   AS       `Custo de Troca Total`,
       V.frete                                               AS 	  `Frete`,
       NULL                                                  AS       `Codigo do Produto`,
       0                                                     AS       `Quantidade Venda Itens`,
       0                                                     AS       `Valor da Venda Itens`,
       0                                                     AS       `Custo da Venda Itens`,
       0                                                     AS       `Quantidade Troca Itens`,
       0                                                     AS       `Valor de Troca Itens`,
       0                                                     AS       `Custo de Troca Itens`
FROM   vendas V
WHERE  V.data_venda >= To_date('2020-01-01', 'yyyy-MM-dd') and V.data_venda <= To_date('2020-12-31', 'yyyy-MM-dd')